In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("play_tennis.csv")
df

day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [4]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for i in df.columns:
    df[i]=le.fit_transform(df[i])

In [5]:
df

day  outlook  temp  humidity  wind  play
0     0        2     1         0     1     0
1     6        2     1         0     0     0
2     7        0     1         0     1     1
3     8        1     2         0     1     1
4     9        1     0         1     1     1
5    10        1     0         1     0     0
6    11        0     0         1     0     1
7    12        2     2         0     1     0
8    13        2     0         1     1     1
9     1        1     2         1     1     1
10    2        2     2         1     0     1
11    3        0     2         0     0     1
12    4        0     1         1     1     1
13    5        1     2         0     0     0

In [6]:
df.play.value_counts()

1    9
0    5
Name: play, dtype: int64

In [10]:
X = df.iloc[:, 1:5]
y = df.iloc[:,-1]

## Defining a function for calculating gini index 

In [7]:
# STEP 1: Calculate gini(D)
def gini_index(y):
    value_counts = y.value_counts()
    n = value_counts.sum()
    p_sum = 0
    for key in value_counts.keys():
        p_sum = p_sum  +  ((value_counts[key] / n )**2) 
    gini = 1 - p_sum
    return gini

## Function to calculate impurity gain 

Here I have assumed threchold as 1.1 for outlook column, just to check the functionality of our code

In [12]:
def impurity_gain(y, X_column):

        # create children
        #left_idxs, right_idxs = _split(X_column, [df.outlook <= 1.1]).flatten()
        left_idxs = np.argwhere([df.outlook <= 1.1])[:,1]
        right_idxs = np.argwhere([df.outlook > 1.1])[:,1]
        
        if len(left_idxs) == 0 or len(right_idxs) == 0:
            return 0
        
        # calculate the weighted avg. entropy of children
        n = len(y)
        n_left, n_right = len(left_idxs), len(right_idxs)
        gini_l, gini_r = gini_index(y[left_idxs]), gini_index(y[right_idxs])
        
        return (n_left/n)*gini_l + (n_right/n)*gini_r

In [13]:
impurity_gain(y, df.outlook)

0.3936507936507937

In [14]:
9/14*(1-((7/9)**2)-((2/9)**2))+(5/14*(1-((2/5)**2)-((3/5)**2)))

0.3936507936507937

### Great, we can see our function is giving desired outputs

### will check the subsets after splitting data 

In [16]:
left_idxs = np.argwhere([df.outlook <= 1.1])[:,1]
right_idxs = np.argwhere([df.outlook > 1.1])[:,1]

In [17]:
y[left_idxs ], y[right_idxs]

(2     1
 3     1
 4     1
 5     0
 6     1
 9     1
 11    1
 12    1
 13    0
 Name: play, dtype: int32,
 0     0
 1     0
 7     0
 8     1
 10    1
 Name: play, dtype: int32)

### Let's create a function to split our data based on threshold 

In [104]:
 def _split(X_column, split_thresh):
        left_idxs = np.argwhere([X_column <= split_thresh])[:,1]
        right_idxs = np.argwhere([X_column > split_thresh])[:,1]
        return left_idxs, right_idxs

__numpy.argwhere()__ function is used to find the indices of array elements that are non-zero, grouped by element.

In [20]:
left_idxs = np.argwhere([df.outlook <= 0])

left_idxs

array([[ 0,  2],
       [ 0,  6],
       [ 0, 11],
       [ 0, 12]], dtype=int64)

In [26]:
left_idxs = np.argwhere([df.outlook <= 0])[:,1]
right_idxs = np.argwhere([df.outlook > 0])[:,1]
left_idxs

array([ 2,  6, 11, 12], dtype=int64)

In [27]:
df.play[left_idxs]

2     1
6     1
11    1
12    1
Name: play, dtype: int32

In [28]:
df.play[right_idxs]

0     0
1     0
3     1
4     1
5     0
7     0
8     1
9     1
10    1
13    0
Name: play, dtype: int32

In [109]:
def impurity_gain(y, X_column,threshold):

        # create children
        left_idxs, right_idxs = _split(X_column, threshold)
        #left_idxs = np.argwhere([df.outlook <= 1.1])[:,1]
        #right_idxs = np.argwhere([df.outlook > 1.1])[:,1]
        
        if len(left_idxs) == 0 or len(right_idxs) == 0:
            return 0
        
        # calculate the weighted avg. entropy of children
        n = len(y)
        n_left, n_right = len(left_idxs), len(right_idxs)
        gini_l, gini_r = gini_index(y[left_idxs]), gini_index(y[right_idxs])
        
        return (n_left/n)*gini_l + (n_right/n)*gini_r

In [179]:
#impurity_gain(y, df.outlook,)

In [76]:
9/14*(1-((7/9)**2)-((2/9)**2))+(5/14*(1-((2/5)**2)-((3/5)**2)))

0.3936507936507937

In [63]:
n_features = X.shape[1]# if not n_features else min(X.shape[1],self.n_features)

In [27]:
X.shape[1]

4

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [31]:
n_feats = X.shape[1]

In [32]:
n_feats

4

In [31]:
np.random.choice(5, 3, replace=False)

array([2, 3, 1])

In [35]:
feat_idxs = np.random.choice(n_feats, n_features, replace=False)

In [36]:
feat_idxs

array([0, 3, 2, 1])

### code to get Bestsplit_threshold

In [38]:
split_idx, split_threshold = None, None
best_gain = -1
for feat_idx in feat_idxs:
    X_column = X.iloc[:, feat_idx]
    thresholds = np.unique(X_column)

    for thr in thresholds:
        # calculate the impurity_gain
        gain = impurity_gain(y, X_column)

        if gain > best_gain:
            best_gain = gain
            split_idx = feat_idx
            split_threshold = thr
                

In [39]:
split_threshold

0

In [40]:
thresholds = np.unique(X_column)

In [41]:
thresholds

array([0, 1, 2])

In [149]:
def _best_split(X, y, feat_idxs):
        best_gain = 0
        split_idx, split_threshold = None, None

        for feat_idx in feat_idxs:
            C = X.iloc[:, feat_idx]
           # print(C)
            thresholds = np.unique(X_column)

            for thr in thresholds:
                # calculate the information gain
                gain = impurity_gain(y, X_column, thr)

                if gain > best_gain:
                    best_gain = gain
                    split_idx = feat_idx
                    split_threshold = thr

        return split_idx, split_threshold

In [152]:
def _grow_tree(X, y, depth=0):
        n_samples, n_feats = X.shape
        n_labels = len(np.unique(y))

        # check the stopping criteria
        if (depth>=max_depth or n_labels==1 or n_samples<min_samples_split):
            leaf_value = most_common_label(y)
            return Node(value=leaf_value)

        feat_idxs = np.random.choice(4, 4, replace=False)
        print(feat_idxs)
        print(1)
        # find the best split
        best_feature, best_thresh = _best_split(X, y, feat_idxs)
        print(best_feature,best_thresh)

        # create child nodes
        left_idxs, right_idxs = _split(X.iloc[:, best_feature], best_thresh)
        print(left_idxs,right_idxs)
        left = _grow_tree(X.iloc[left_idxs, :], y[left_idxs], depth+1)
        right = _grow_tree(X.iloc[right_idxs, :], y[right_idxs], depth+1)
        #return best_feature, best_thresh, left, right

In [121]:
y[left_idxs]

2     1
6     1
11    1
12    1
Name: play, dtype: int32

In [148]:
X.iloc[:, 1]

0     1
1     1
2     1
3     2
4     0
5     0
6     0
7     2
8     0
9     2
10    2
11    2
12    1
13    2
Name: temp, dtype: int32

In [124]:
X.iloc[left_idxs, :]

outlook  temp  humidity  wind
2         0     1         0     1
6         0     0         1     0
11        0     2         0     0
12        0     1         1     1

In [43]:
from collections import Counter

def _most_common_label(y):
    counter = y.value_counts()
    value = counter.index[0]
    return value

In [153]:
min_samples_split=2
max_depth=100
n_features=None

_grow_tree(X,y,0)

[1 3 2 0]
1
1 1
[ 0  1  2  4  5  6  8 12] [ 3  7  9 10 11 13]
[2 3 0 1]
1


KeyError: '[3, 7, 9, 10, 11, 13] not in index'

In [ ]:
_best_split(X, y, feat_idxs)

In [174]:
right=[3, 7, 9, 10, 11, 13]

In [ ]:
_best_split(X.iloc[right,:] y[right], feat_idxs)

In [157]:
feat_idxs

array([2, 0, 3, 1])

In [155]:
X.iloc[right,:]

outlook  temp  humidity  wind
3         1     2         0     1
7         2     2         0     1
9         1     2         1     1
10        2     2         1     0
11        0     2         0     0
13        1     2         0     0

In [156]:
y[right]

3     1
7     0
9     1
10    1
11    1
13    0
Name: play, dtype: int32

In [175]:
_best_split(X=X.iloc[right,:], y = y[right], feat_idxs=feat_idxs)

IndexError: positional indexers are out-of-bounds

In [177]:
right

[3, 7, 9, 10, 11, 13]

In [176]:
X.iloc[right,:]

IndexError: positional indexers are out-of-bounds

In [161]:
X

outlook  temp  humidity  wind
3         1     2         0     1
7         2     2         0     1
9         1     2         1     1
10        2     2         1     0
11        0     2         0     0
13        1     2         0     0

In [163]:
feat_idxs

array([2, 0, 3, 1])

In [165]:
split_idx, split_threshold = None, None
best_gain = -1
for feat_idx in feat_idxs:
    X_column = X.iloc[:, feat_idx]
    thresholds = np.unique(X_column)

    for thr in thresholds:
        # calculate the impurity_gain
        gain = impurity_gain(y, X_column,thr)

        if gain > best_gain:
            best_gain = gain
            split_idx = feat_idx
            split_threshold = thr
                

In [166]:
split_threshold

1

In [167]:
split_idx

0

In [ ]:
best_feature, best_thresh = _best_split(X, y, feat_idxs)

In [140]:
X.iloc[left_idxs, :]

outlook  temp  humidity  wind
0         2     1         0     1
1         2     1         0     0
2         0     1         0     1
4         1     0         1     1
5         1     0         1     0
6         0     0         1     0
8         2     0         1     1
12        0     1         1     1

In [138]:
left_idxs = [0 , 1 , 2  ,4 , 5,  6, 8, 12]

In [91]:
feat_idxs = np.random.choice(4, 4, replace=False)

In [92]:
feat_idxs

array([1, 3, 2, 0])

In [70]:
n_features = X.shape[1]

In [71]:
n_features

4

In [90]:
feat_idxs

3

In [59]:
n_samples, n_feats = X.shape

In [72]:
n_feats

4

In [62]:
n_features

In [113]:
feat_idxs = np.random.choice(4, 4, replace=False)

In [114]:
feat_idxs

array([2, 0, 3, 1])

In [115]:
# find the best split
best_feature, best_thresh = _best_split(X, y, feat_idxs)

In [116]:
best_feature

1

In [117]:
best_thresh

1

In [119]:
X.iloc[:, 1]

0     1
1     1
2     1
3     2
4     0
5     0
6     0
7     2
8     0
9     2
10    2
11    2
12    1
13    2
Name: temp, dtype: int32